version: '3'
services:
  client:
    image: evaluacion-client
    build:
      context: ./client
    ports:
      - "5174:5173"
    env_file:
      - ./client/.env.production
    command: npm run build
    volumes:
      - client-build:/app/build # Comparte la carpeta build como un volumen
    depends_on:
      - server

  server:
    image: evaluacion-server
    build:
      context: ./server
    ports:
      - "4001:4001"
    env_file:
      # - ./server/config.env
      - ./server/.env.production
    volumes:
      - client-build:/app/public # Usa el volumen compartido para la carpeta public
    command: ["node", "server.js"]

  fastapi_backend: # Tu servicio para el servidor de Python (FastAPI)
    build:
      context: ./fastapi
      args:
        HF_AUTH_TOKEN_BUILD: "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"
        DEVICE_BUILD: "cpu"
        MODEL_SIZE_BUILD: "medium"
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 192.168.1.39
      DB_USER: raul
      DB_PASS: loquecallamoslosadmin1
      DB_NAME: calidad
      HF_AUTH_TOKEN: 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
    volumes:
      - ./fastapi:/app # Monta el código local para facilitar el desarrollo

volumes:
  client-build:
