services:
  client:
    image: evaluacion-client
    build:
      context: ./client
    env_file:
      - ./client/.env.production
    volumes:
      - client-build:/app/build
    depends_on:
      - server

  server:
    image: evaluacion-server
    build:
      context: ./server
    ports:
      - "4001:4001"
    env_file:
      - ./server/.env.production
    volumes:
      - client-build:/app/public
      - ./server/resultados:/app/server/resultados
      - ./server/audios:/app/server/audios
    command: ["node", "server.js"]

  fastapi_backend:
    build:
      context: ./fastapi
      args:
        HF_AUTH_TOKEN_BUILD: "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"
        DEVICE_BUILD: "cpu"
        MODEL_SIZE_BUILD: "medium"
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 192.168.1.36
      DB_USER: cob_bd
      DB_PASS: 33nKVs4@nC
      DB_NAME: calidad
      DEVICE: "cpu"
      MODEL_SIZE: "medium"
      COMPUTE_TYPE: "int8"
      HF_AUTH_TOKEN: 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
    volumes: []

volumes:
  client-build:
